CREATE DATABASE JUEGO_CARTA;
USE JUEGO_CARTA;


CREATE TABLE JUGADOR(
    JUG_ID INT PRIMARY KEY AUTO_INCREMENT,
    JUG_NOMBRE VARCHAR(30),
    JUG_APELLIDO VARCHAR(30),
    JUG_EDAD INT,
    JUG_EMAIL VARCHAR(50)
);

CREATE TABLE TIPO_USUARIO(
   TUSU_ID INT PRIMARY KEY AUTO_INCREMENT,
   TUSU_NOMBRE VARCHAR(30)
);

CREATE TABLE USUARIO(
    USU_ID INT PRIMARY KEY AUTO_INCREMENT,
    USU_NOMBRE VARCHAR(30),
    USU_PASS VARCHAR(30),
    TUSU_ID INT,
    JUG_ID INT,
    
    FOREIGN KEY(TUSU_ID) REFERENCES TIPO_USUARIO(TUSU_ID),
    FOREIGN KEY(JUG_ID) REFERENCES JUGADOR(JUG_ID)
);

CREATE TABLE MAZO(
    MAZ_ID INT PRIMARY KEY AUTO_INCREMENT,
    JUG_ID INT,
    
    FOREIGN KEY(JUG_ID) REFERENCES JUGADOR(JUG_ID)
);

CREATE TABLE TIPO_CARTA(
    TCAR_ID INT PRIMARY KEY AUTO_INCREMENT,
    TCAR_NOMBRE VARCHAR(30)
);

CREATE TABLE CARTA(
    CAR_ID INT PRIMARY KEY AUTO_INCREMENT,
    CAR_NOMBRE VARCHAR(30),
    CAR_ATAQUE INT,
    CAR_DEFENSA INT,
    TCAR_ID INT,
    
    FOREIGN KEY(TCAR_ID) REFERENCES TIPO_CARTA(TCAR_ID)
);


CREATE TABLE ASIGNACION_MAZO(
    ASIG_ID INT PRIMARY KEY AUTO_INCREMENT,
    MAZ_ID INT,
    CAR_ID INT,
    
    FOREIGN KEY(MAZ_ID) REFERENCES MAZO(MAZ_ID),
    FOREIGN KEY(CAR_ID) REFERENCES CARTA(CAR_ID)
);



CREATE TABLE TIPO_ARENA(
    TARE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TARE_NOMBRE VARCHAR(30)
);


CREATE TABLE ARENA(
    ARE_ID  INT PRIMARY KEY AUTO_INCREMENT,
    ARE_NOMBRE VARCHAR(30),
    ARE_MINIMO INT,
    ARE_MAXIMO INT,
    TARE_ID INT,
    
    FOREIGN KEY(TARE_ID) REFERENCES TIPO_ARENA(TARE_ID)
);

CREATE TABLE PARTIDA(
    PAR_ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    HORA TIME,
    ARE_ID  INT,
    
    FOREIGN KEY(ARE_ID) REFERENCES ARENA(ARE_ID)
);

CREATE TABLE JUGADORES(
    JUGS_ID INT PRIMARY KEY AUTO_INCREMENT,
    JUG_ID INT,
    PAR_ID INT,
    
    FOREIGN KEY(JUG_ID) REFERENCES JUGADOR(JUG_ID),
    FOREIGN KEY(PAR_ID) REFERENCES PARTIDA(PAR_ID)
);


CREATE TABLE COPAS(
    COP_ID INT PRIMARY KEY AUTO_INCREMENT,
    COP_CANTIDAD INT,
    JUG_ID INT,
    PAR_ID INT,
    
    FOREIGN KEY(JUG_ID) REFERENCES JUGADOR(JUG_ID),
    FOREIGN KEY(PAR_ID) REFERENCES PARTIDA(PAR_ID)

);


-- INSERT TIPO USER 
INSERT INTO tipo_usuario(TUSU_NOMBRE) VALUES('Manager');
INSERT INTO tipo_usuario(TUSU_NOMBRE) VALUES('Administrador');
INSERT INTO tipo_usuario(TUSU_NOMBRE) VALUES('Supervisor');
INSERT INTO tipo_usuario(TUSU_NOMBRE) VALUES('Participante');
-- insert juagador 
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Pedro','Ramirez',48,'pedro@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Miguel','Ramirez',25,'miguel@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Lazaro','Quich',45,'lazaro@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Daniel','Tun',12,'daniel@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Ervin','Cacoj',34,'ervin@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Alex','Carrillo',36,'alex@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Carlos','Tujal',15,'carlos@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Estefany','Tunay',45,'estefany@gmail.com');
INSERT INTO jugador(JUG_NOMBRE,JUG_APELLIDO,JUG_EDAD,JUG_EMAIL)  VALUES('Mishell','Garcia',23,'mishell@gmail.com');

-- insert usuario
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Pedro','12345',1,1);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Miguel','12345',1,2);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Lazaro','12345',2,3);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Daniel','12345',2,4);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Ervin','12345',3,5);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Alex','12345',3,6);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Carlos','12345',4,7);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Estefany','12345',4,8);
INSERT into usuario(USU_NOMBRE,USU_PASS,TUSU_ID,JUG_ID) VALUES('Mishell','12345',4,9);

-- insert tipo carta 
INSERT INTO tipo_carta(TCAR_NOMBRE) VALUES('Comunes');
INSERT INTO tipo_carta(TCAR_NOMBRE) VALUES('Especiales');
INSERT INTO tipo_carta(TCAR_NOMBRE) VALUES('Epicas');
INSERT INTO tipo_carta(TCAR_NOMBRE) VALUES('Legendarias');

-- insert carta 

INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Esqueleto', 91, 91, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Espiritu de hielo', 91, 190, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Duende', 99, 167, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Descarga',159, 0, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Murcielago',67, 67, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Espiritu de fuego',178, 91, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bola de nieve',159, 0, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Arquera',89, 252, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Flechas',243, 0, 1);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Caballero',167, 1350, 1);

INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Golem de hielo',70 ,994 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Megaesbirro',258 ,695 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Lanzadardos',100 ,216 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bola de fuego',572 ,0 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Mini pekka',598 ,1129 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Mosquetera',176 ,598 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Montapuercos',264 ,1408 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Valquiria',221 ,1657 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Maquina voladora',142 ,510 , 2);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Torre bombardera',184 ,1126 , 2);

INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Ejercito esqueleto',67 ,67 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Guardias',0 ,90 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Tornado',140 ,0 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bebe dragon',133 ,1064 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Cazador',691 ,696 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Hielo',101 ,0 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Veneno',600 ,0 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Principe oscuro',206 ,1030 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Principe',325 ,1615 , 3);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bruja',69 ,787 , 3);


INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Tronco',240 ,0 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Minero',160 ,1000 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Princesa',140 ,216 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Fantasma real',216 ,1000 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Mago de hielo',75 ,590 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bandida',160 ,780 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Bruja nocturna',260 ,750 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Dragon infernal real',30 ,1070 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Leniador',200 ,1060 , 4);
INSERT INTO carta(CAR_NOMBRE,CAR_ATAQUE,CAR_DEFENSA,TCAR_ID) values('Arquero magico',96 ,490 , 4);

-- insert tipo arena 

INSERT INTO tipo_arena(TARE_NOMBRE) values('Estadio duende');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Foso de huesos');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Coliseo bárbaro');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Fuerte del Pekka');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Valle de los hechizos');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Taller de constructor');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Arena Real'); 
INSERT INTO tipo_arena(TARE_NOMBRE) values('Pico Helado');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Arena Selvática');
INSERT INTO tipo_arena(TARE_NOMBRE) values('Arena Montepuerco');


-- insert arena 

INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 1',0, 400,1);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 2',400,800 ,2);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 3',800,1100 ,3);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 4',1100,1400 ,4);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 5',1400,1700 ,5);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 6',1700,2000 ,6);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 7',2000,2300 ,7);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 8',2300,2600,8);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 9',2600,3000,9);
INSERT INTO arena(ARE_NOMBRE,ARE_MINIMO,ARE_MAXIMO,TARE_ID) VALUES('Arena 10',3000,3400,10);

-- insert mazo 

INSERT INTO mazo(JUG_ID) VALUES(1);
INSERT INTO mazo(JUG_ID) VALUES(1);
INSERT INTO mazo(JUG_ID) VALUES(1);

INSERT INTO mazo(JUG_ID) VALUES(2);
INSERT INTO mazo(JUG_ID) VALUES(2);
INSERT INTO mazo(JUG_ID) VALUES(2);

INSERT INTO mazo(JUG_ID) VALUES(3);
INSERT INTO mazo(JUG_ID) VALUES(3);
INSERT INTO mazo(JUG_ID) VALUES(3);

INSERT INTO mazo(JUG_ID) VALUES(4);
INSERT INTO mazo(JUG_ID) VALUES(4);
INSERT INTO mazo(JUG_ID) VALUES(4);

INSERT INTO mazo(JUG_ID) VALUES(5);
INSERT INTO mazo(JUG_ID) VALUES(5);
INSERT INTO mazo(JUG_ID) VALUES(5);

INSERT INTO mazo(JUG_ID) VALUES(6);
INSERT INTO mazo(JUG_ID) VALUES(6);
INSERT INTO mazo(JUG_ID) VALUES(6);

INSERT INTO mazo(JUG_ID) VALUES(7);
INSERT INTO mazo(JUG_ID) VALUES(7);
INSERT INTO mazo(JUG_ID) VALUES(7);

INSERT INTO mazo(JUG_ID) VALUES(8);
INSERT INTO mazo(JUG_ID) VALUES(8);
INSERT INTO mazo(JUG_ID) VALUES(8);

INSERT INTO mazo(JUG_ID) VALUES(9);
INSERT INTO mazo(JUG_ID) VALUES(9);
INSERT INTO mazo(JUG_ID) VALUES(9);




-- inserta asignacion 

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(1,8);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,9);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,10);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,11);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,12);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,13);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,14);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,15);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(2,16);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,17);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,18);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,19);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,20);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,21);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,22);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,23);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(3,24);


INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,25);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,26);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,27);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,28);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,29);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,30);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,31);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(4,32);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,33);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,34);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,35);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,36);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,37);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,38);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,39);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(5,40);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(6,8);

--   segunda parte 
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(7,8);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,9);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,10);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,11);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,12);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,13);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,14);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,15);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(8,16);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,17);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,18);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,19);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,20);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,21);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,22);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,23);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(9,24);


INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,25);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,26);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,27);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,28);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,29);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,30);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,31);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(10,32);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,33);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,34);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,35);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,36);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,37);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,38);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,39);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(11,40);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(12,8);

-- 1
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(13,8);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,9);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,10);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,11);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,12);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,13);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,14);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,15);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(14,16);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,17);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,18);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,19);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,20);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,21);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,22);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,23);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(15,24);

-- 2 
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,1);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,2);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,3);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,4);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,5);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,6);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,7);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(16,8);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,9);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,10);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,11);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,12);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,13);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,14);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,15);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(17,16);

INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,17);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,18);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,19);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,20);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,21);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,22);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,23);
INSERT INTO asignacion_mazo(MAZ_ID,CAR_ID) VALUES(18,24);


-- insertar partidas 

INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);

INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);
INSERT INTO partida(FECHA,HORA,ARE_ID) VALUES(NOW(),NOW(),1);

-- insert juegadores 

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,1);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,1);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,2);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(3,2);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,3);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(4,3);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,4);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(5,4);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,5);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(6,5);



INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,6);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(1,6);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,7);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(3,7);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,8);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(4,8);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,9);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(5,9);

INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(2,10);
INSERT INTO jugadores(JUG_ID,PAR_ID) VALUES(6,10);

-- inserta copas 

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,1,1);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,2,1);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,1,2);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,3,2);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,1,3);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,4,3);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,1,4);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,5,4);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,1,5);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,6,5);



INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,2,6);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,1,6);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,2,7);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,3,7);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,2,8);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,4,8);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,2,9);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,5,9);

INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(3,2,10);
INSERT INTO copas(COP_CANTIDAD,JUG_ID,PAR_ID) VALUES(0,6,10);

